name: critter_app
description: Nookipedia critter viewer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.0
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/startup.mp3
    - assets/images/loading_screen.png
    - assets/images/background.jpg

  fonts:
  - family: CritterFont
    fonts:
      - asset: assets/fonts/FinkHeavy.ttf


